stages:
  prepare:
    cmd: python src/data_preparation.py
    deps:
    - data/raw/churn.csv
    - src/data_preparation.py
    outs:
    - data/processed
    - data/training/churn_features.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/train.py
    outs:
    - models/churn_model.pkl
